version: "3.8"
services:
  smigoal-model:
    container_name: smigoal-model
    build:
      dockerfile: Dockerfile
      context: ./model
    image: ajroot/smigoal-model
    volumes:
      - /home/ubuntu/SmiGoal/model/src/model_100000_data.pt:/model/model_100000_data.pt
    ports:
      - "5000:5000"
  smigoal-server:
    container_name: smigoal-server
    build:
      dockerfile: Dockerfile
      context: ./server
    image: ajroot/smigoal-server
    ports:
      - "8080:8080"